# Generated by Django 6.1.1 on 2026-09-18 20:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("invoice", "Счёт"),
                            ("contract", "Контракт"),
                            ("act", "Акт"),
                            ("report", "Отчёт"),
                            ("other", "Другое"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="Тип документа",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Черновик"),
                            ("uploaded", "Загружен"),
                            ("processing", "В обработке"),
                            ("on_approval", "На согласовании"),
                            ("approved", "Согласован"),
                            ("rejected", "Отклонён"),
                            ("failed", "Ошибка обработки"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="documents/%Y/%m",
                        verbose_name="Файл",
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Исходное имя файла",
                    ),
                ),
                (
                    "mime_type",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="MIME-тип"
                    ),
                ),
                (
                    "size_bytes",
                    models.PositiveBigIntegerField(
                        default=0, verbose_name="Размер (байт)"
                    ),
                ),
                (
                    "extracted_data",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Извлечённые данные"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлён"),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Владелец",
                    ),
                ),
            ],
            options={
                "verbose_name": ("Документ",),
                "verbose_name_plural": ("Документы",),
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status"], name="documents_d_status_07369e_idx"
                    ),
                    models.Index(
                        fields=["doc_type"], name="documents_d_doc_typ_4a1a00_idx"
                    ),
                ],
            },
        ),
    ]
