# Generated by Django 6.1.1 on 2026-09-19 15:17

from django.db import migrations, models

import documents.validators


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="documents/%Y/%m",
                validators=[
                    documents.validators.validate_file_size,
                    documents.validators.validate_file_extension,
                ],
                verbose_name="Файл",
            ),
        ),
    ]
